### ISSUE TITLE
Files of the code  are missing?

### ISSUE THREAD

**Issue by Davidchenw** [Yongquan-He/HIP-network#1]
Thanks for sharing the code, but some files are missing making it difficult to reproduce the experiment. For example, in train.py
" from exp.module.vocab.vocabulary import Vocabulary
from exp.module.structural.comgcn_model_dgl import CompGCN_DistMult_DGL, CompGCN_ConvE_DGL
from exp.module.structural.compgcn_model import CompGCN_TransE, CompGCN_DistMult, CompGCN_ConvE
from exp.module.temporal.temporal_attention_layer import TemporalSelfAttentionLayer
from exp.util.utils import *
"
exp.module.vocab.vocabulary, exp.module.structural.compgcn_model and exp.util.utils are missing.
Could you please provide these missing files?

**Comment by Yongquan-He** [comment]
Thanks for reminding me. I will check in the next couple of days. And upload the code again.
