### ISSUE TITLE
Cannot meet the requirements

### ISSUE THREAD

**Issue by meteorlin** [Yongquan-He/HIP-network#3]
Thx for sharing code.
I have created a virtual environment to install requirements, but there are some installation problems in pygpu and torch-scatter, which is "Could not find a version that satisfies the requirement pygpu" and "OSError: [WinError 127]" respectively.
How to solve these problems? 
Thx in advance!

**Comment by Yongquan-He** [comment]
You can try to install torch-scatter with clear version. This dependency may be a little hard to install. And for you problem, I guess you can install it according to your cuda version.

**Comment by meteorlin** [comment]
Thx for your quick reply and now the program runs. Here is my solution:
1. I checked the version of cuda version in my computer via `nvidia-smi` and found it is 11.1, which is the cause of the problems mentioned above.
2. I installed the modified requirements according to the 11.1 cuda version. The followed is my modified requirements and the related version of torch and torch-scatter can be found in [this site](https://pytorch.org/get-started/previous-versions/) and [this site](https://pytorch-geometric.com/whl/) respectively.
```
helper==2.4.2
networkx==2.5
numpy==1.17.3
nltk==3.4.5
dgl-cu100==0.5.2
ordered-set==4.0.2
packaging==19.2
pandas==0.25.2
Pillow==6.2.0
# pygpu==0.7.6
scikit-learn==0.21.3
scipy==1.3.1
spacy==2.1.8
# torch==1.7.0+cu101
# torch-scatter==2.0.5
# torchvision==0.8.1+cu101
torch==1.8.1+cu111
torch-scatter==2.0.8
torchvision==0.9.1+cu111
tqdm==4.36.1
```
3. After installing the requirements, I inserted some essential code into `utiils.py` according to #2 :
```python
def get_param(shape):
    param = nn.Parameter(torch.Tensor(*shape))
    nn.init.xavier_normal_(param, gain=nn.init.calculate_gain('relu'))
    return param
```
4. Before run the `train.py`, there are some changes need to be applied in [`compgcn_conv_basis.py`](https://github.com/Yongquan-He/HIP-network/blob/9625528bd83568745106f211e7a0ca43e896d1e8/exp/module/structural/compgcn_conv.py#L3), [`compgcn_conv.py`](https://github.com/Yongquan-He/HIP-network/blob/9625528bd83568745106f211e7a0ca43e896d1e8/exp/module/structural/compgcn_conv_basis.py#L4), [`compgcn_model.py`](https://github.com/Yongquan-He/HIP-network/blob/9625528bd83568745106f211e7a0ca43e896d1e8/exp/module/structural/compgcn_model.py#L4) and [`utils.py`](https://github.com/Yongquan-He/HIP-network/blob/9625528bd83568745106f211e7a0ca43e896d1e8/exp/util/utils.py#L366). 
    1. The first three files need to be modified from the `from exp.util.helper import *` to `from exp.util.utils import *`
    2. The last one needs to be removed the `return` symbol in `366` line.
At present, the program can run temporarily. If there is any problem, I will reopen the issue.
Thx again!

**Comment by Yongquan-He** [comment]
Thanks very much for your feedback. Due to the influence of different graph learning tools. I have tried many tools, and modified several versions to optimize the running speed of multi-step reasoning.  So some version confused, I will check again as soon as possible.
Thanks again for your contribution!
